/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/providers/models': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * List Models
     * @description List available models for a given provider and API key.
     */
    post: operations['list_models_api_providers_models_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Job
     * @description Upload ALTO/PAGE XML files and start a correction job.
     *
     *     Upload concurrency is reserved by ``UploadAdmissionMiddleware``
     *     BEFORE the multipart body is read: by the time this handler runs,
     *     FastAPI has already parsed (and spooled) the files, so a slot check
     *     here would fire after the full upload cost was paid. The whole
     *     handler executes inside the middleware's reservation.
     */
    post: operations['create_job_api_jobs_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Job
     * @description Poll the status of a correction job.
     */
    get: operations['get_job_api_jobs__job_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Cancel Job
     * @description Plan V2.2 — request cooperative cancellation. Idempotent.
     *
     *     Sets the job's cancellation event; the pipeline's ``should_abort``
     *     probe (polled between pages and chunks) trips on the next check and
     *     the runner lands the job in CANCELLED with no output promoted. A
     *     request on an already-settled job acknowledges without effect —
     *     the response body always carries the CURRENT status.
     */
    post: operations['cancel_job_api_jobs__job_id__cancel_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Job Events
     * @description SSE stream of correction job events. Plan V2.4 — EventSource
     *     cannot set headers, so access uses the events-scoped ``?sig=``
     *     credential minted at job creation (never the capability token).
     */
    get: operations['job_events_api_jobs__job_id__events_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/events-url': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Renew Events Url
     * @description Mint a fresh events-scoped SSE URL (token-gated).
     *
     *     EventSource cannot set headers, so the stream route takes a signed
     *     ``?sig=``. Credentials are deliberately short-lived; a client
     *     reconnecting after a drop (or after any amount of time — the job
     *     timeout can be disabled entirely) calls this with its capability
     *     token instead of holding a credential sized to the whole run.
     */
    get: operations['renew_events_url_api_jobs__job_id__events_url_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/download-url': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Mint Download Url
     * @description Mint a short-lived signed download URL (token-gated).
     *
     *     The browser then navigates to it and streams the artefact natively —
     *     no ``fetch().blob()`` buffering the whole file in renderer memory,
     *     and the capability token itself still never travels in a URL (a
     *     leaked download credential expires in minutes and opens nothing
     *     else).
     */
    get: operations['mint_download_url_api_jobs__job_id__download_url_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/download': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Download Job
     * @description Download corrected XML file(s).
     *
     *     Accessible with the capability token (header) or a download-scoped
     *     signed ``?sig=`` minted by ``GET /{job_id}/download-url`` — the
     *     header-less variant exists so the BROWSER can stream the artefact
     *     natively instead of the app buffering it through a blob.
     */
    get: operations['download_job_api_jobs__job_id__download_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/trace': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Job Trace
     * @description Return the job's CorrectionReport (§9) — per-line text traces.
     *
     *     The response IS the versioned ``CorrectionReport`` JSON (the same
     *     document persisted as ``trace.json``): ``report_version`` / ``run_id``
     *     (== ``job_id``) / ``total_lines`` / ``lines``. The pre-unification
     *     ``{job_id, total_lines, lines}`` JobTrace shape is gone.
     */
    get: operations['get_job_trace_api_jobs__job_id__trace_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/diff': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Job Diff
     * @description Return per-line OCR vs corrected diff data for a completed job.
     *
     *     Thin adapter: the projection lives in ``app.api.read_models.build_diff``
     *     (pure, unit-tested). ``get_completed_job`` already 404s on a missing
     *     manifest, but an ``assert`` would disappear under ``python -O`` (bandit
     *     B101), so keep a real runtime guard.
     */
    get: operations['get_job_diff_api_jobs__job_id__diff_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/layout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Job Layout
     * @description Return structural layout data (blocks + lines with ALTO coordinates).
     *
     *     Thin adapter over ``app.api.read_models.build_layout`` (pure, unit-tested).
     */
    get: operations['get_job_layout_api_jobs__job_id__layout_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/images/{image_name}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Job Image
     * @description Serve a source scan image for a job. Plan V2.4 — <img> tags cannot
     *     set headers, so access uses the images-scoped ``?sig=`` credential
     *     appended by the layout endpoint (never the capability token).
     */
    get: operations['get_job_image_api_jobs__job_id__images__image_name__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/reviews': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Reviews */
    get: operations['get_reviews_api_jobs__job_id__reviews_get']
    /**
     * Put Reviews
     * @description Record or replace judgements on lines of this job.
     *
     *     Idempotent per line: sending the same line twice replaces its review
     *     rather than appending, so a reader who changes their mind is not fighting
     *     an append-only log. The timestamp is stamped here rather than trusted
     *     from the client — a review's date is a fact about the server.
     */
    put: operations['put_reviews_api_jobs__job_id__reviews_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/reviews/activity': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Review Activity
     * @description A reader interacted with the review UI; renew its idle timeout.
     */
    post: operations['review_activity_api_jobs__job_id__reviews_activity_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/reviews/export': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Export Reviews
     * @description Export saved annotations and their source/candidate evidence.
     */
    get: operations['export_reviews_api_jobs__job_id__reviews_export_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** Body_create_job_api_jobs_post */
    Body_create_job_api_jobs_post: {
      /** Files */
      files: string[]
      /** Provider */
      provider: string
      /** Api Key */
      api_key: string
      /** Model */
      model: string
      /**
       * Geometric Pairing
       * @default true
       */
      geometric_pairing: boolean
    }
    /** CreateJobResponse */
    CreateJobResponse: {
      /** Job Id */
      job_id: string
      /** Job Token */
      job_token?: string | null
      /** Events Url */
      events_url?: string | null
    }
    /**
     * DownloadUrlResponse
     * @description A freshly minted download URL (download-scoped ``?sig=``, short TTL).
     *
     *     Lets the browser stream the artefact natively (navigation /
     *     ``<a href>``) instead of buffering it through ``fetch().blob()`` —
     *     the capability token itself still never travels in a URL.
     */
    DownloadUrlResponse: {
      /** Download Url */
      download_url: string
    }
    /**
     * EventsUrlResponse
     * @description A freshly minted SSE URL (events-scoped ``?sig=``, short TTL).
     *
     *     Renewal endpoint for reconnections: the creation-time ``events_url``
     *     is deliberately short-lived, so a client re-opening the stream later
     *     asks for a new credential with its capability token instead of
     *     holding a credential sized to the whole run.
     */
    EventsUrlResponse: {
      /** Events Url */
      events_url: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * JobStatus
     * @description Lifecycle state of a correction job, surfaced to API clients.
     * @enum {string}
     */
    JobStatus:
      | 'queued'
      | 'started'
      | 'running'
      | 'completed'
      | 'completed_with_fallbacks'
      | 'completed_with_review_required'
      | 'completed_with_withheld_files'
      | 'failed'
      | 'cancel_requested'
      | 'cancelled'
    /** JobStatusResponse */
    JobStatusResponse: {
      /** Job Id */
      job_id: string
      status: components['schemas']['JobStatus']
      /**
       * Total Lines
       * @default 0
       */
      total_lines: number
      /**
       * Lines Modified
       * @default 0
       */
      lines_modified: number
      /**
       * Chunks Total
       * @default 0
       */
      chunks_total: number
      /**
       * Retries
       * @default 0
       */
      retries: number
      /**
       * Fallbacks
       * @default 0
       */
      fallbacks: number
      /**
       * Review Lines
       * @default 0
       */
      review_lines: number
      /** Review Reasons */
      review_reasons?: {
        [key: string]: number
      }
      /** Withheld Files */
      withheld_files?: {
        [key: string]: string
      }
      /** Duration Seconds */
      duration_seconds?: number | null
      /** Error */
      error?: string | null
    }
    /**
     * LineReview
     * @description One reader's judgement on one line.
     */
    LineReview: {
      /** Page Id */
      page_id: string
      /** Line Id */
      line_id: string
      verdict: components['schemas']['ReviewVerdict']
      /** Transcription */
      transcription?: string | null
      /** Note */
      note?: string | null
      /** Reviewed At */
      reviewed_at?: string | null
    }
    /** ListModelsRequest */
    ListModelsRequest: {
      provider: components['schemas']['Provider']
      /** Api Key */
      api_key: string
    }
    /** ListModelsResponse */
    ListModelsResponse: {
      provider: components['schemas']['Provider']
      /** Models */
      models: components['schemas']['ModelInfo'][]
    }
    /**
     * ModelInfo
     * @description An LLM model description as returned by ``BaseProvider.list_models``.
     */
    ModelInfo: {
      /** Id */
      id: string
      /** Label */
      label: string
      /**
       * Supports Structured Output
       * @default true
       */
      supports_structured_output: boolean
      /** Context Window */
      context_window?: number | null
    }
    /**
     * Provider
     * @description Identifier for an LLM vendor. Each value maps to one ``BaseProvider``.
     * @enum {string}
     */
    Provider: 'openai' | 'anthropic' | 'mistral' | 'google'
    /**
     * ReviewBatch
     * @description Reviews arrive in batches: a reader works through a page, not a line.
     */
    ReviewBatch: {
      /** Reviews */
      reviews: components['schemas']['LineReview'][]
    }
    /**
     * ReviewVerdict
     * @description What the reader concluded about the engine's decision on this line.
     * @enum {string}
     */
    ReviewVerdict: 'accepted' | 'refused' | 'transcribed'
    /** ReviewsResponse */
    ReviewsResponse: {
      /** Job Id */
      job_id: string
      /** Reviews */
      reviews: components['schemas']['LineReview'][]
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_models_api_providers_models_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ListModelsRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ListModelsResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_job_api_jobs_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_create_job_api_jobs_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CreateJobResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_job_api_jobs__job_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobStatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  cancel_job_api_jobs__job_id__cancel_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobStatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  job_events_api_jobs__job_id__events_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  renew_events_url_api_jobs__job_id__events_url_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EventsUrlResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  mint_download_url_api_jobs__job_id__download_url_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DownloadUrlResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  download_job_api_jobs__job_id__download_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_job_trace_api_jobs__job_id__trace_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_job_diff_api_jobs__job_id__diff_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_job_layout_api_jobs__job_id__layout_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_job_image_api_jobs__job_id__images__image_name__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
        image_name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_reviews_api_jobs__job_id__reviews_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewsResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  put_reviews_api_jobs__job_id__reviews_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewBatch']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewsResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  review_activity_api_jobs__job_id__reviews_activity_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  export_reviews_api_jobs__job_id__reviews_export_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
